image: certpl/docker-ci-base:latest

stages:
  - test
  - deploy

services:
- docker:dind

test_style_py2:
  image: python:2.7
  stage: test
  script:
  - python --version
  - pip install flake8
  - flake8 . --exclude=venv,docs,logo --max-line-length 121
  
test_style_py3:
  image: python:3.6
  stage: test
  script:
  - python3 --version
  - pip3 install flake8
  - flake8 . --exclude=venv,docs,logo --max-line-length 121

deploy_py3:
  stage: deploy
  only:
  - master
  script:
  - docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PASSWORD" https://dr.cert.pl
  - deploy --push karton2

deploy_py2:
  stage: deploy
  only:
  - master
  script:
  - docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PASSWORD" https://dr.cert.pl
  - deploy --push karton2-py2
