stages:
  - test
  - deploy

services:
- docker:dind

test_style_py2:
  image: python:2.7
  stage: test
  script:
  - python --version
  - pip install flake8
  - flake8 . --exclude=venv,docs,logo --max-line-length 121
  
test_style_py3:
  image: python:3.6
  stage: test
  script:
  - python3 --version
  - pip3 install flake8
  - flake8 . --exclude=venv,docs,logo --max-line-length 121

deploy_pypi:
  image: python:3.6
  stage: deploy
  only:
    refs:
      - master
    variables:
      - $PYPI_LOGIN
      - $PYPI_PASSWORD
  script:
    - python setup.py bdist_wheel
    - pip install twine
    - twine upload -u "$PYPI_LOGIN" -p "$PYPI_PASSWORD" --skip-existing dist/*
