# ONLY FOR LOCAL DEVELOPMENT
#
# remember to setup Splunk after first run
# http://localhost:8000 -> Login: admin / Password: kartondev
# -> Settings -> Indexes -> New Index
# -> Index Name: karton -> Save

version: '3'
services:
    redis:
        image: redis
        ports:
            - "127.0.0.1:6379:6379"
    minio:
        image: minio/minio
        command: server /data
        volumes:
            - /tmp/minio:/data
        ports:
            - "127.0.0.1:9000:9000"
        environment:
            - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    splunk:
        image: splunk/splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_PASSWORD=kartondev
        ports:
            - "0.0.0.0:8000:8000"
            - "127.0.0.1:8089:8089"

