# ONLY FOR LOCAL DEVELOPMENT
services:
  redis:
    image: library/redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 10
  silo:
    image: pgsty/silo:RELEASE.2026-09-16T00-00-00Z
    command: "server --address 0.0.0.0:9000 --console-address :9001 /data"
    volumes:
      - /tmp/silo:/data
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - MINIO_ROOT_USER=karton-test-access
      - MINIO_ROOT_PASSWORD=karton-test-key
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
  system:
    build:
      context: ..
      dockerfile: system.Dockerfile
    env_file:
      - karton-vars.env
    command:
      - "--setup-bucket"
    depends_on:
      silo:
        condition: service_healthy
      redis:
        condition: service_healthy
  gateway:
    build:
      context: ..
      dockerfile: gateway.Dockerfile
    env_file:
      - karton-vars.env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      silo:
        condition: service_healthy
      redis:
        condition: service_healthy
  logger:
    build:
      context: ..
      dockerfile: dev/logger.Dockerfile
    env_file:
      - karton-vars.env
    depends_on:
      - system
