name: Build and push docker images
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_core:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push the image
        uses: docker/build-push-action@v4
        with:
          tags: |
            certpl/karton-system:${{ github.sha }}
            certpl/karton-system:master
          push: ${{ github.event_name == 'push' }}
          # Flux v1 doesn't support OCI-compliant manifests
          provenance: false
          platforms: linux/arm64,linux/amd64
