name: Build and push docker images
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_core:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push the image
        uses: docker/build-push-action@v2.2.1
        with:
          tags: |
            certpl/karton-system:${{ github.sha }}
            certpl/karton-system:master
          push: ${{ github.event_name == 'push' }}
